# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  fetch-stream:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 
  
    - name: Fetch stream url
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python fetch_stream.py > stream_url.txt
        echo "::set-env name=STREAM_URL::$(cat stream_url.txt)"
        
    - name: Update file in repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl \
          -X PUT \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"message": "Update file", "content": "'$(base64 stream_url.txt)'" }' \
          "https://api.github.com/repos/ofer1992/surf_dashboard/contents/stream_url.txt"

